[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcpguard"
version = "0.1.0"
description = "A security firewall for AI agents."
authors = [
  { name="Rushali Moteria", email="rushalimoteria@gmail.com" },
]
dependencies = [
  "PyYAML",
]

